- name:  bond
  user: root
  gather_facts: false
  vars:
  - eth_dir: /etc/sysconfig/network-scripts/
  hosts: sy
  tasks:
#  - name: yum libselinux-python
#    yum: state=present name=libselinux-python
  - name: copy eth
    shell: chdir={{eth_dir}} mv ifcfg-{{item}} ifcfg-{{item}}.baktwo
    with_items:
      - eth0
      - eth1
    ignore_errors: True
  - name: touch eth
    shell: chdir={{eth_dir}} touch {{item}}
    with_items:
      - ifcfg-eth0
      - ifcfg-eth1
      - ifcfg-bond0
    ignore_errors: True
  - name: touch modules.conf
    file: path=/etc/modules.conf state=touch
    ignore_errors: True
  - name: echo eth0
    lineinfile: dest={{eth_dir}}/ifcfg-eth0 line={{item}}
    with_items:
      - DEVICE=eth0
      - USERCTL=no
      - BOOTPROTO=none
      - ONBOOT=yes
      - MASTER=bond0
      - SLAVE=yes
  - name: echo eth1
    lineinfile: dest={{eth_dir}}/ifcfg-eth1 line={{item}}
    with_items:
      - DEVICE=eth1
      - USERCTL=no
      - BOOTPROTO=none
      - ONBOOT=yes
      - MASTER=bond0
      - SLAVE=yes
  - name: echo bond0
    lineinfile: dest={{eth_dir}}/ifcfg-bond0 line={{item}}
    with_items:
      - DEVICE=bond0
      - BONDING_OPTS="mode=1 miimon=100"
      - BOOTPROTO=none
      - IPADDR
      - NETMASK=255.255.255.0
      - GATEWAY
      - DNS1=202.106.0.20
      - BROADCAST
      - ONBOOT=yes
  - name: echo module.conf
    lineinfile: dest=/etc/modules.conf line={{item}}
    with_items:
      - "alias bond0 bonding"
      - "options bond0 miimon=100 mode=1"
      - USERCTL=no
  - name: sed ip
    shell: ifconfig eth0 | awk '/inet addr/{print $2}' | awk -F ":" '{print $2}'|xargs -I {} sed -i "s@IPADDR@IPADDR={}@" /etc/sysconfig/network-scripts/ifcfg-bond0 
  - name: sed GATEWAY
    shell: ifconfig eth0 | awk '/inet addr/{print $2}' | awk -F ":" '{print $2}'|awk -F "." '{print $3}'|xargs -I {} sed -i "s@GATEWAY@GATEWAY=172.16.{}.1@" /etc/sysconfig/network-scripts/ifcfg-bond0 
  - name: sed BROADCAST
    shell: ifconfig eth0 | awk '/inet addr/{print $2}' | awk -F ":" '{print $2}'|awk -F "." '{print $3}'|xargs -I {} sed -i "s@BROADCAST@BROADCAST=172.16.{}.255@" /etc/sysconfig/network-scripts/ifcfg-bond0 
#  - name: network restarted
#    service: name=network state=restarted
